Library Structures 번역 ~ global libraries
yeonjuan/Typescript-Handbook-ko pull request #181
Opened 2020-03-29 12:08 UTC by guyeol

리뷰 부탁드립니다

2020-04-01 07:53 UTC, dvlprsh requested changes

2020-04-01 07:53 UTC, dvlprsh commented on declaration files/Library Structures.md
> +일반적으로, 선언 파일을 *구조*하는 방법은 라이브러리를 사용하는 방법에 따라 다릅니다.
[제안]
```suggestion
일반적으로, 선언 파일을 *구조화*하는 방법은 라이브러리를 사용하는 방법에 따라 다릅니다.
```

2020-04-01 07:53 UTC, dvlprsh commented on declaration files/Library Structures.md
> +이 템플릿들로 시작하면 더 빠르게 진행할 수 있습니다.
```suggestion
이 템플릿으로 시작하면 더 빠르게 진행할 수 있습니다.
```

2020-04-01 07:53 UTC, dvlprsh commented on declaration files/Library Structures.md
> +["이름 충돌 방지" 각주](#preventing-name-conflicts)를 반드시 읽어야 합니다.
```suggestion
["이름 충돌 방지" 각주](#preventing-name-conflicts)를 반드시 읽어보세요.
```

2020-04-01 07:54 UTC, dvlprsh commented
고생하셨습니다!!!

2020-04-02 03:36 UTC, dvlprsh approved these changes

2020-04-03 08:00 UTC, yeonjuan approved these changes

2020-04-04 04:41 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +JavaScript에서 사용할 라이브러리를 제공하는 방법은 여러 가지가 있고, 이에 맞추어 선언 파일을 작성해야 합니다.
```suggestion
JavaScript에 사용할 라이브러리를 제공하는 여러가지 방법이 있고, 이에 맞추어 선언 파일을 작성해야 합니다.
```

2020-04-04 04:42 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +이 가이드는 일반적인 라이브러리 패턴을 식별하는 방법과, 그 패턴에 상응하는 선언 파일을 작성하는 방법에 대해 다룹니다.
```suggestion
이 가이드는 일반적인 라이브러리 패턴 식별 방법과 그 패턴에 상응하는 선언 파일 작성 방법에 대해 다룹니다.
```

조금 줄여봤는데 어떤가요?

2020-04-04 04:42 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +주요 라이브러리 구조화 패턴의 각 유형은 해당 파일이 [템플릿](./Templates.md) 섹션에 있습니다.
```suggestion
주요 라이브러리 구조화 패턴의 각 유형은 [템플릿](./Templates.md) 섹션에 있습니다.
```

2020-04-04 04:44 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +첫 번째로, TypeScript 선언 파일이 나타낼 수 있는 라이브러리 종류를 다뤄보겠습니다.
```suggestion
먼저 TypeScript 선언 파일이 나타낼 수 있는 라이브러리 종류를 다뤄보겠습니다.
```

2020-04-04 04:44 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +*사용법*과 *코드*를 기반으로 구조를 식별하는 방법에 대한 힌트를 제공할 것입니다.
```suggestion
*사용법*과 *코드*를 기반으로 구조를 식별하는 방법에 대한 힌트를 제공합니다.
```

2020-04-04 04:45 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +본인에게 더 편한 것을 사용할 것을 추천합니다.
```suggestion
본인에게 더 편한 것을 사용하세요.
```

2020-04-04 04:46 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +많은 라이브러리는 사용을 위해 간단히 하나 이상의 전역 변수를 노출합니다.
```suggestion
많은 라이브러리는 간단하게 사용하기 위해 한 개 이상의 전역 변수를 노출합니다.
```

2020-04-04 04:47 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +HTML 스크립트 태그로 라이브러리를 사용하는 방법에 대해 라이브러리 문서에서 지침을 볼 수 있습니다:
```suggestion
HTML 스크립트 태그로 라이브러리를 사용하는 방법은 라이브러리 문서에서 지침을 볼 수 있습니다:
```

2020-04-04 04:48 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +* 최상위 `var`문 이나 `function`선언
```suggestion
* 최상위 레벨 `var`문 이나 `function`선언
```

2020-04-04 04:49 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +* 최상위 `var`문 이나 `function`선언
`수준`이나 `레벨`을 추가하는 건 어떨까요?

2020-04-04 04:49 UTC, Bumkeyy commented on declaration files/Library Structures.md
> +### 전역 라이브러리 예졔 (Examples of Global Libraries)
```suggestion
### 전역 라이브러리 예제 (Examples of Global Libraries)
```

2020-04-04 04:50 UTC, bumkeyy approved these changes

2020-04-04 04:50 UTC, Bumkeyy commented
수고하셨습니다 👍

2020-04-05 14:07 UTC, merged